spring.application.name=authservice
#spring.datasource.url=jdbc:mysql://mysql-container:3306/testdb
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8091

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

resilience4j.retry,instances.externalservice.max-attempts=3
resilience4j.retry.instances.externalservice.wait-duration=2s

resilience4j.timelimiter.instances.externalService.timeout-duration=3s

resilience4j.ratelimiter.instances.rateLimiterApi.limit-for-period=5

resilience4j.ratelimiter.instances.rateLimiterApi.limit-refresh-period=30s

resilience4j.ratelimiter.instances.rateLimiterApi.timeout-duration=0